version: '3.9'

services:
  script:
    build:
      context: .
      dockerfile: Dockerfile.compose-example
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network

networks:
  app-network:
    driver: bridge